"""Tests for Rust acceleration wrappers and their Python fallback paths.

These tests pass whether or not the ``_nexus3d_rust`` native module is built.
"""

from __future__ import annotations

import struct
from pathlib import Path


# ---------------------------------------------------------------------------
# gcode_rust — wrapper + fallback
# ---------------------------------------------------------------------------


class TestGcodeRust:
    def test_wrapper_imports_without_native(self):
        from app.services import gcode_rust

        assert gcode_rust._rust_scan is None  # native module not built

    def test_gcode_scan_returns_none_when_native_missing(self, tmp_path: Path):
        from app.services import gcode_rust

        path = tmp_path / "missing.gcode"
        result = gcode_rust.gcode_scan(path)
        assert result is None

    def test_gcode_scan_returns_dict_when_native_present(self, monkeypatch):
        """If the native module were available, this is what the return shape looks like."""
        expected = {
            "sha256": "abc123",
            "slicer_name": "OrcaSlicer",
            "slicer_version": "2.3.0",
            "printer_model": "MK4",
            "nozzle_diameter_mm": 0.4,
            "layer_height_mm": 0.2,
            "infill_percent": 15.0,
            "estimated_time_s": 5400,
            "filament_weight_g": 45.3,
            "filament_length_mm": 15200.5,
            "filament_cost": 3.2,
            "material_type": "PLA",
            "thumbnail_png": b"\x89PNG...",
        }

        def fake_scan(_path: str) -> dict:
            return expected

        monkeypatch.setattr("app.services.gcode_rust._rust_scan", fake_scan)
        from app.services import gcode_rust  # re-import with monkeypatched

        result = gcode_rust.gcode_scan(Path("fake.gcode"))
        assert result is not None
        assert result["sha256"] == "abc123"
        assert result["slicer_name"] == "OrcaSlicer"


# ---------------------------------------------------------------------------
# raster_rust — wrapper + fallback
# ---------------------------------------------------------------------------


class TestRasterRust:
    def test_wrapper_imports_without_native(self):
        from app.services import raster_rust

        assert raster_rust._rasterise is None

    def test_rasterise_returns_none_when_native_missing(self):
        from app.services import raster_rust

        import numpy as np

        tri = np.zeros((1, 3, 3), dtype=np.float64)
        shade = np.ones(1, dtype=np.float64)
        result = raster_rust.rasterise(tri, shade, 64, 48)
        assert result is None

    def test_rasterise_returns_none_always(self, monkeypatch):
        """rasterise unconditionally returns None (Rust rasteriser is disabled)."""
        import numpy as np

        import app.services.raster_rust as raster_rust

        tri = np.zeros((2, 3, 3), dtype=np.float64)
        shade = np.array([0.5, 0.8], dtype=np.float64)
        result = raster_rust.rasterise(tri, shade, 100, 200)
        assert result is None


# ---------------------------------------------------------------------------
# ingestion — gcode_strategy fallback
# ---------------------------------------------------------------------------


class TestIngestionGcodeStrategy:
    def test_falls_back_to_pure_python(self, monkeypatch, tmp_path: Path):
        """_gcode_strategy.process should use pure Python when Rust is missing."""
        from app.services import ingestion

        # Create a minimal G-code file.
        gcode = (
            "; generated by OrcaSlicer 2.3.0 on Linux\n"
            "; printer_model = TestRig\n"
            "; nozzle_diameter = 0.4\n"
            "; layer_height = 0.2\n"
            "; sparse_infill_density = 15%\n"
            "; estimated printing time (normal mode) = 1h 30m 0s\n"
            "; total filament used [g] = 45.3\n"
            "; total filament length [mm] = 15200.5\n"
            "; total filament cost = 3.20\n"
            "; filament_type = PLA\n"
            "G1 X0 Y0 Z0\n"
        )
        path = tmp_path / "test.gcode"
        path.write_text(gcode)

        strategy = ingestion._gcode_strategy()
        meta, thumb = strategy.process(path)

        assert meta["slicer_name"] == "OrcaSlicer"
        assert meta["printer_model"] == "TestRig"
        assert meta["nozzle_diameter_mm"] == 0.4
        assert meta["estimated_time_s"] == 5400
        assert meta["filament_weight_g"] == 45.3
        assert meta["material_type"] == "PLA"
        assert thumb is None  # no embedded thumbnail


# ---------------------------------------------------------------------------
# mesh_render — thumbnail rendering (raster_rust fallback)
# ---------------------------------------------------------------------------


class TestMeshRenderThumbnail:
    def test_render_thumbnail_falls_back_to_pure_numpy(self, tmp_path: Path):
        """render_thumbnail should produce valid PNG even without Rust rasteriser."""
        from app.services.mesh_render import render_thumbnail
        from app.services.mesh_processing import _load_mesh

        # Minimal binary STL (ASCII would also work, but binary is smaller).
        # Header (80 bytes) + triangle count (4 bytes, little-endian u32 = 1) + 1 triangle (50 bytes)
        stl_path = tmp_path / "cube.stl"
        stl = _make_minimal_stl_bytes()
        stl_path.write_bytes(stl)

        png = render_thumbnail(_load_mesh, stl_path, width=64, height=48)
        assert png is not None
        assert len(png) > 100  # reasonable PNG overhead
        assert png[:4] == b"\x89PNG"  # PNG magic

    def test_render_thumbnail_handles_missing_file(self, tmp_path: Path):
        from app.services.mesh_render import render_thumbnail
        from app.services.mesh_processing import _load_mesh

        path = tmp_path / "nonexistent.stl"
        png = render_thumbnail(_load_mesh, path, width=64, height=48)
        assert png is None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_minimal_stl_bytes() -> bytes:
    """Create a minimal binary STL with a single triangle."""
    header = b"\x00" * 80
    tri_count = struct.pack("<I", 1)

    # One triangle: normal (12 bytes = 3 * f32) + vertices (36 bytes) + attr (2 bytes)
    normal = struct.pack("<3f", 0.0, 0.0, 1.0)
    v1 = struct.pack("<3f", 0.0, 0.0, 0.0)
    v2 = struct.pack("<3f", 10.0, 0.0, 0.0)
    v3 = struct.pack("<3f", 0.0, 10.0, 0.0)
    attr = b"\x00\x00"

    return header + tri_count + normal + v1 + v2 + v3 + attr
