/// Combined single-pass G-code scanner: sha256 + metadata parse + thumbnail extract.
///
/// Opens the file once, streams it through sha256 while simultaneously
/// capturing the first/last 64 KB for regex metadata extraction and
/// line-scanning for embedded `; thumbnail begin … end` blocks.
///
/// This replaces three separate Python passes (``sha256_file``,
/// ``gcode_parser._read_window``, ``thumbnail.extract``) with one sequential
/// read.

use std::fs::File;
use std::io::{BufRead, BufReader, Read, Seek, SeekFrom};
use std::path::Path;

use base64::Engine;
use regex::Regex;
use sha2::{Digest, Sha256};

const HEAD_TAIL_BYTES: usize = 64 * 1024; // 64 KB

// ---------------------------------------------------------------------------
// Public result struct
// ---------------------------------------------------------------------------

#[derive(Debug, Default, Clone)]
pub struct GcodeMetadata {
    pub slicer_name: Option<String>,
    pub slicer_version: Option<String>,
    pub printer_model: Option<String>,
    pub nozzle_diameter_mm: Option<f64>,
    pub layer_height_mm: Option<f64>,
    pub infill_percent: Option<f64>,
    pub estimated_time_s: Option<i64>,
    pub filament_weight_g: Option<f64>,
    pub filament_length_mm: Option<f64>,
    pub filament_cost: Option<f64>,
    pub material_type: Option<String>,
}

#[derive(Debug)]
pub struct GcodeScan {
    pub sha256: String,
    pub meta: GcodeMetadata,
    pub thumbnail_png: Option<Vec<u8>>,
}

// ---------------------------------------------------------------------------
// Duration parsing
// ---------------------------------------------------------------------------

/// Parse a human-readable duration string into total seconds.
/// Accepts `1h 23m 45s`, `2d 4h`, `90s`, or a bare seconds integer/float.
/// Returns `None` when the string cannot be parsed.
fn parse_duration(raw: &str) -> Option<i64> {
    let s = raw.trim();
    if s.is_empty() {
        return None;
    }
    // First try the 1h 23m pattern.
    let dur_re: Regex = Regex::new(r"(?i)(\d+)\s*([dhms])").unwrap();
    let mut total: i64 = 0;
    let mut found = false;
    for caps in dur_re.captures_iter(s) {
        let val: i64 = caps[1].parse().ok()?;
        let unit = caps[2].to_ascii_lowercase();
        let secs = match unit.as_str() {
            "d" => 86400,
            "h" => 3600,
            "m" => 60,
            "s" => 1,
            _ => return None,
        };
        total += val * secs;
        found = true;
    }
    if found {
        return Some(total);
    }
    // Fallback: plain integer / float seconds.
    s.parse::<f64>().ok().map(|v| v as i64)
}

// ---------------------------------------------------------------------------
// Metadata regex extraction
// ---------------------------------------------------------------------------

const PATTERNS: &[(&str, &str)] = &[
    ("slicer_version", r"(?i);\s*generated by\s+(.+?)\s+on"),
    ("printer_model", r"(?i);\s*printer_model\s*=\s*(.+)"),
    ("nozzle_diameter_mm", r"(?i);\s*nozzle_diameter\s*=\s*([\d.]+)"),
    ("layer_height_mm", r"(?i);\s*layer_height\s*=\s*([\d.]+)"),
    ("infill_percent", r"(?i);\s*sparse_infill_density\s*=\s*([\d.]+)\s*%?"),
    (
        "estimated_time_raw",
        r"(?i);\s*estimated printing time.*?=\s*(.+)",
    ),
    ("filament_weight_g", r"(?i);\s*total filament used \[g\]\s*=\s*([\d.]+)"),
    (
        "filament_length_mm",
        r"(?i);\s*total filament length \[mm\]\s*=\s*([\d.]+)",
    ),
    ("filament_cost", r"(?i);\s*total filament cost\s*=\s*([\d.]+)"),
    ("material_type", r"(?i);\s*filament_type\s*=\s*(\S+)"),
];

fn derive_slicer_name(version: &str) -> Option<&'static str> {
    let lower = version.to_ascii_lowercase();
    if lower.contains("orca") {
        Some("OrcaSlicer")
    } else if lower.contains("prusa") {
        Some("PrusaSlicer")
    } else if lower.contains("bambu") {
        Some("BambuStudio")
    } else if lower.contains("super") {
        Some("SuperSlicer")
    } else {
        None
    }
}

fn apply_patterns(text: &str) -> GcodeMetadata {
    let mut meta = GcodeMetadata::default();
    for (key, pat) in PATTERNS {
        let re = Regex::new(pat).unwrap(); // compiled once; acceptable overhead here
        let Some(caps) = re.captures(text) else {
            continue;
        };
        let value = caps[1].trim().to_string();
        match *key {
            "estimated_time_raw" => {
                meta.estimated_time_s = parse_duration(&value);
            }
            "slicer_version" => {
                meta.slicer_name = derive_slicer_name(&value).map(String::from);
                meta.slicer_version = Some(value);
            }
            "nozzle_diameter_mm"
            | "layer_height_mm"
            | "infill_percent"
            | "filament_weight_g"
            | "filament_length_mm"
            | "filament_cost" => {
                let _ = value.parse::<f64>().ok().map(|v| {
                    let field: &mut Option<f64> = match *key {
                        "nozzle_diameter_mm" => &mut meta.nozzle_diameter_mm,
                        "layer_height_mm" => &mut meta.layer_height_mm,
                        "infill_percent" => &mut meta.infill_percent,
                        "filament_weight_g" => &mut meta.filament_weight_g,
                        "filament_length_mm" => &mut meta.filament_length_mm,
                        "filament_cost" => &mut meta.filament_cost,
                        _ => unreachable!(),
                    };
                    *field = Some(v);
                });
            }
            _ => {
                let field: &mut Option<String> = match *key {
                    "printer_model" => &mut meta.printer_model,
                    "material_type" => &mut meta.material_type,
                    _ => unreachable!(),
                };
                *field = Some(value);
            }
        }
    }
    meta
}

// ---------------------------------------------------------------------------
// Thumbnail extraction state machine
// ---------------------------------------------------------------------------

struct ThumbBlock {
    width: u32,
    height: u32,
    b64: String,
}

struct ThumbScanner {
    in_block: bool,
    width: u32,
    height: u32,
    buf: String,
    best: Option<ThumbBlock>,
    begin_re: Regex,
    end_re: Regex,
    tail: String, // partial line carried over from previous chunk
}

impl ThumbScanner {
    fn new() -> Self {
        Self {
            in_block: false,
            width: 0,
            height: 0,
            buf: String::new(),
            best: None,
            begin_re: Regex::new(r"(?i);\s*thumbnail begin\s+(\d+)x(\d+)\s+(\d+)").unwrap(),
            end_re: Regex::new(r"(?i);\s*thumbnail end").unwrap(),
            tail: String::new(),
        }
    }

    fn feed(&mut self, chunk: &str) {
        // Prepend any partial line left from the previous chunk.
        let text = if self.tail.is_empty() {
            chunk.to_string()
        } else {
            let combined = self.tail.clone() + chunk;
            self.tail.clear();
            combined
        };

        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            if !self.in_block {
                if let Some(caps) = self.begin_re.captures(line) {
                    self.width = caps[1].parse().unwrap_or(0);
                    self.height = caps[2].parse().unwrap_or(0);
                    self.buf.clear();
                    self.in_block = true;
                }
                continue;
            }
            // Inside a thumbnail block.
            if self.end_re.is_match(line) {
                let block = ThumbBlock {
                    width: self.width,
                    height: self.height,
                    b64: std::mem::take(&mut self.buf),
                };
                let area = block.width * block.height;
                let replace = match &self.best {
                    Some(b) => area > b.width * b.height,
                    None => true,
                };
                if replace {
                    self.best = Some(block);
                }
                self.in_block = false;
                continue;
            }
            // Strip leading "; " or ";".
            let stripped = line
                .strip_prefix("; ")
                .or_else(|| line.strip_prefix(';'))
                .unwrap_or(line);
            self.buf.push_str(stripped);
        }

        // If the last line in this chunk didn't end with a newline it might
        // be split across chunks — carry it forward.
        // Actually, `lines()` consumes `\n`, so a line that doesn't end with
        // `\n` in the original chunk is the last partial line.
        // We detect this by checking whether `chunk` ended with `\n`.
        if !chunk.ends_with('\n') {
            // The final line was incomplete; extract and carry it.
            if let Some(pos) = text.rfind('\n') {
                self.tail = text[pos + 1..].to_string();
            } else {
                self.tail = text;
            }
        }
    }

    fn finish(mut self) -> Option<Vec<u8>> {
        // If still inside a block at EOF, decode what we have (best-effort).
        if self.in_block && !self.buf.is_empty() {
            let block = ThumbBlock {
                width: self.width,
                height: self.height,
                b64: std::mem::take(&mut self.buf),
            };
            let area = block.width * block.height;
            let replace = match &self.best {
                Some(b) => area > b.width * b.height,
                None => true,
            };
            if replace {
                self.best = Some(block);
            }
        }
        self.best.and_then(|b| {
            base64::engine::general_purpose::STANDARD
                .decode(b.b64.trim().as_bytes())
                .ok()
        })
    }
}

// ---------------------------------------------------------------------------
// Main entry point: combined scan
// ---------------------------------------------------------------------------

/// Open *path* once, compute sha256, capture head/tail windows for metadata
/// regex extraction, and scan for embedded PrusaSlicer/OrcaSlicer thumbnails.
///
/// Panics (propagating to a Python exception) if the file cannot be opened.
pub fn gcode_scan(path: &Path) -> std::io::Result<GcodeScan> {
    let mut file = File::open(path)?;
    let file_len = file.metadata()?.len() as usize;

    let mut hasher = Sha256::new();
    let mut head_buf = Vec::with_capacity(HEAD_TAIL_BYTES.min(file_len));
    let mut tail_ring: Vec<u8> = Vec::new();
    let mut thumb_scanner = ThumbScanner::new();

    // Read first 64 KB (or whole file if smaller than 128 KB).
    let head_size = HEAD_TAIL_BYTES.min(file_len);
    let mut chunk = vec![0u8; head_size];
    file.read_exact(&mut chunk)?;
    hasher.update(&chunk);
    head_buf = chunk;

    if file_len > head_size {
        // Stream the middle in 1 MiB chunks.
        let chunk_size = 1024 * 1024;
        let mut buf = vec![0u8; chunk_size];
        loop {
            let n = file.read(&mut buf)?;
            if n == 0 {
                break;
            }
            let slice = &buf[..n];
            hasher.update(slice);

            // Maintain a ring buffer of the last 64 KB for tail extraction.
            tail_ring.extend_from_slice(slice);
            if tail_ring.len() > HEAD_TAIL_BYTES {
                let drop = tail_ring.len() - HEAD_TAIL_BYTES;
                tail_ring.drain(..drop);
            }

            // Feed to thumbnail scanner (lossy UTF-8 is fine for comment lines).
            let text = String::from_utf8_lossy(slice);
            thumb_scanner.feed(&text);
        }
    } else {
        // Small file: tail and head are the same.
        tail_ring = head_buf.clone();
        thumb_scanner.feed(&String::from_utf8_lossy(&head_buf));
    }

    let sha256_hex = format!("{:x}", hasher.finalize());

    // Assemble head + tail window for regex matching.
    let head_text = String::from_utf8_lossy(&head_buf);
    let tail_text = String::from_utf8_lossy(&tail_ring);
    let window = format!("{}\n{}", head_text, tail_text);
    let meta = apply_patterns(&window);
    let thumbnail_png = thumb_scanner.finish();

    Ok(GcodeScan {
        sha256: sha256_hex,
        meta,
        thumbnail_png,
    })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_duration() {
        assert_eq!(parse_duration("1h 23m 45s"), Some(5025));
        assert_eq!(parse_duration("2d 4h"), Some(187200));
        assert_eq!(parse_duration("90s"), Some(90));
        assert_eq!(parse_duration("90"), Some(90));
        assert_eq!(parse_duration("3.5"), Some(3));
        assert_eq!(parse_duration(""), None);
    }

    #[test]
    fn test_derive_slicer_name() {
        assert_eq!(derive_slicer_name("OrcaSlicer 2.3.0"), Some("OrcaSlicer"));
        assert_eq!(derive_slicer_name("PrusaSlicer-2.9.0"), Some("PrusaSlicer"));
        assert_eq!(
            derive_slicer_name("BambuStudio 1.10"),
            Some("BambuStudio")
        );
        assert_eq!(derive_slicer_name(""), None);
    }

    #[test]
    fn test_metadata_pattern_match() {
        let text = "; PrusaSlicer 2.9.0 on Linux\n\
                    ; printer_model = MK4\n\
                    ; nozzle_diameter = 0.4\n\
                    ; layer_height = 0.2\n\
                    ; sparse_infill_density = 15%\n\
                    ; estimated printing time (normal mode) = 1h 30m 0s\n\
                    ; total filament used [g] = 45.3\n\
                    ; total filament length [mm] = 15200.5\n\
                    ; total filament cost = 3.20\n\
                    ; filament_type = PLA\n";
        let meta = apply_patterns(text);
        assert_eq!(meta.slicer_name.as_deref(), Some("PrusaSlicer"));
        assert_eq!(meta.printer_model.as_deref(), Some("MK4"));
        assert_eq!(meta.nozzle_diameter_mm, Some(0.4));
        assert_eq!(meta.layer_height_mm, Some(0.2));
        assert_eq!(meta.infill_percent, Some(15.0));
        assert_eq!(meta.estimated_time_s, Some(5400));
        assert_eq!(meta.filament_weight_g, Some(45.3));
        assert_eq!(meta.filament_length_mm, Some(15200.5));
        assert_eq!(meta.filament_cost, Some(3.2));
        assert_eq!(meta.material_type.as_deref(), Some("PLA"));
    }

    #[test]
    fn test_thumb_scanner_single_block() {
        let mut scanner = ThumbScanner::new();
        // A tiny 1-pixel PNG (simplified for test).
        let b64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==";
        scanner.feed(&format!("; thumbnail begin 1x1 {}\n; {b64}\n; thumbnail end\n", b64.len()));
        let result = scanner.finish().unwrap();
        assert!(result.len() > 10); // reasonable PNG header
    }

    #[test]
    fn test_thumb_scanner_picks_largest() {
        let mut scanner = ThumbScanner::new();
        let small_b64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==";
        let large_b64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==";
        scanner.feed(&format!(
            "; thumbnail begin 100x100 {}\n; {small_b64}\n; thumbnail end\n",
            small_b64.len()
        ));
        scanner.feed(&format!(
            "; thumbnail begin 200x200 {}\n; {large_b64}\n; thumbnail end\n",
            large_b64.len()
        ));
        let result = scanner.finish().unwrap();
        assert_eq!(result.len(), 69); // 200x200 is larger, so decoded block = 69 bytes
    }
}
