"""OrcaSlicer / PrusaSlicer G-code metadata parser.

Reads only the head + tail of the file (slicer comments live there).
Never raises on malformed input — unknown fields return None.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, Optional

from app.core.logging import get_logger

logger = get_logger(__name__)

_HEAD_BYTES = 64 * 1024
_TAIL_BYTES = 64 * 1024

# Compiled patterns. Each capture group 1 is the value.
_PATTERNS: dict[str, re.Pattern[str]] = {
    "slicer_version": re.compile(r";\s*generated by\s+(.+?)\s+on", re.IGNORECASE),
    "printer_model": re.compile(r";\s*printer_model\s*=\s*(.+)", re.IGNORECASE),
    "nozzle_diameter_mm": re.compile(
        r";\s*nozzle_diameter\s*=\s*([\d.]+)", re.IGNORECASE
    ),
    "layer_height_mm": re.compile(r";\s*layer_height\s*=\s*([\d.]+)", re.IGNORECASE),
    "infill_percent": re.compile(
        r";\s*sparse_infill_density\s*=\s*([\d.]+)\s*%?", re.IGNORECASE
    ),
    "estimated_time_raw": re.compile(
        r";\s*estimated printing time.*?=\s*(.+)", re.IGNORECASE
    ),
    "filament_weight_g": re.compile(
        r";\s*total filament used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE
    ),
    "filament_length_mm": re.compile(
        r";\s*total filament length \[mm\]\s*=\s*([\d.]+)", re.IGNORECASE
    ),
    "filament_cost": re.compile(
        r";\s*total filament cost\s*=\s*([\d.]+)", re.IGNORECASE
    ),
    "material_type": re.compile(r";\s*filament_type\s*=\s*(\S+)", re.IGNORECASE),
}

_DURATION_RE = re.compile(r"(\d+)\s*([dhms])", re.IGNORECASE)
_DURATION_UNITS = {"d": 86400, "h": 3600, "m": 60, "s": 1}


def parse_duration(s: str) -> Optional[int]:
    """Parse '1h 23m 45s' / '2d 4h' / '90s' into seconds. Returns None on failure."""
    if not s:
        return None
    matches = _DURATION_RE.findall(s)
    if not matches:
        # try plain integer seconds
        try:
            return int(float(s.strip()))
        except (ValueError, TypeError):
            return None
    total = 0
    for value, unit in matches:
        total += int(value) * _DURATION_UNITS[unit.lower()]
    return total


def _read_window(path: Path) -> str:
    """Return head + tail of the file as a single decoded string."""
    size = path.stat().st_size
    with path.open("rb") as fh:
        head = fh.read(min(_HEAD_BYTES, size))
        if size > _HEAD_BYTES + _TAIL_BYTES:
            fh.seek(-_TAIL_BYTES, 2)
            tail = fh.read(_TAIL_BYTES)
        else:
            tail = b""
    blob = head + b"\n" + tail
    return blob.decode("utf-8", errors="replace")


def parse(path: Path) -> Dict[str, Any]:
    """Extract slicer metadata from a G-code file. Returns a dict ready for Metadata()."""
    out: Dict[str, Any] = {
        "slicer_name": None,
        "slicer_version": None,
        "printer_model": None,
        "nozzle_diameter_mm": None,
        "layer_height_mm": None,
        "infill_percent": None,
        "estimated_time_s": None,
        "filament_weight_g": None,
        "filament_length_mm": None,
        "filament_cost": None,
        "material_type": None,
    }

    try:
        text = _read_window(path)
    except OSError as e:
        logger.warning("gcode parse: cannot read %s: %s", path, e)
        return out

    for key, pat in _PATTERNS.items():
        m = pat.search(text)
        if not m:
            continue
        value = m.group(1).strip()

        if key == "estimated_time_raw":
            out["estimated_time_s"] = parse_duration(value)
        elif key == "slicer_version":
            out["slicer_version"] = value
            # Try to also derive slicer_name from the same line.
            lower = value.lower()
            if "orca" in lower:
                out["slicer_name"] = "OrcaSlicer"
            elif "prusa" in lower:
                out["slicer_name"] = "PrusaSlicer"
            elif "bambu" in lower:
                out["slicer_name"] = "BambuStudio"
            elif "super" in lower:
                out["slicer_name"] = "SuperSlicer"
        elif (
            key.endswith("_mm")
            or key.endswith("_g")
            or key in {"filament_cost", "infill_percent"}
        ):
            try:
                out[key] = float(value)
            except ValueError:
                out[key] = None
        else:
            out[key] = value

    return out
