import { expect, type Page } from "@playwright/test";

// The backend dedupes files by content hash, so the bytes must be unique per
// model — embed the name so each upload creates a distinct model.
function gcodeFor(name: string): string {
  return [
    `; generated by e2e for ${name}`,
    "; estimated printing time (normal mode) = 30m 12s",
    "; filament used [g] = 6.8",
    "G28",
    "G1 Z0.2 F300",
  ].join("\n");
}

export function modelCard(page: Page, name: string) {
  return page.locator('a[href^="/models/"]').filter({ hasText: name });
}

// Upload a G-code-only model through the real upload flow and wait for the
// async backend ingestion to surface it in the library. Returns when visible.
export async function uploadGcodeModel(page: Page, name: string): Promise<void> {
  await page.goto("/");
  await page.getByRole("button", { name: "Upload" }).click();
  await expect(page.getByRole("dialog", { name: "Upload model" })).toBeVisible();
  await page.locator('input[accept=".gcode,.g,.gco"]').setInputFiles({
    name: "part.gcode",
    mimeType: "text/plain",
    buffer: Buffer.from(gcodeFor(name)),
  });
  await page.getByPlaceholder("e.g. Bracket v2").fill(name);
  await page.getByRole("button", { name: /upload to vault/i }).click();
  await expect(page.getByRole("dialog", { name: "Upload model" })).toHaveCount(0);

  await expect(async () => {
    await page.goto("/");
    await expect(modelCard(page, name)).toBeVisible({ timeout: 2_000 });
  }).toPass({ timeout: 60_000 });
}
