/* eslint-disable react-refresh/only-export-components */
import { Children, cloneElement, isValidElement, type ReactElement, type ReactNode } from "react";

import { useOptionalI18n, type Locale } from "@/lib/i18n";

const ES_PHRASES: ReadonlyArray<readonly [string, string]> = [
  ["Vault configuration and display preferences", "Configuración de la bóveda y preferencias de visualización"],
  ["Portable archive with models, metadata, print history, and original artifacts", "Archivo portátil con modelos, metadatos, historial de impresión y artefactos originales"],
  ["Export a versioned archive for migration to another PrintStash installation. Accounts, credentials, settings, and trash are excluded.", "Exporta un archivo versionado para migrar a otra instalación de PrintStash. Se excluyen cuentas, credenciales, ajustes y papelera."],
  ["Download your searchable library context for spreadsheets, audits, migrations, or local AI prompts.", "Descarga el contexto consultable de tu biblioteca para hojas de cálculo, auditorías, migraciones o IA local."],
  ["Metadata only — no raw STL/3MF/G-code files", "Solo metadatos, sin archivos STL/3MF/G-code originales"],
  ["Server status and vault configuration", "Estado del servidor y configuración de la bóveda"],
  ["API server status and version", "Estado y versión del servidor API"],
  ["SQLite by default, Postgres optional", "SQLite por defecto; Postgres opcional"],
  ["Configured vault storage", "Almacenamiento configurado de la bóveda"],
  ["Tracked in the database", "Registrados en la base de datos"],
  ["Hierarchical tree entries", "Entradas del árbol jerárquico"],
  ["Flat tag vocabulary size", "Tamaño del vocabulario de etiquetas"],
  ["Live library entries", "Entradas activas de la biblioteca"],
  ["Configured devices", "Dispositivos configurados"],
  ["File storage backend, S3 credentials, and backup retention", "Backend de archivos, credenciales S3 y retención de copias"],
  ["Changes to the storage backend require an application restart.", "Cambiar el backend de almacenamiento requiere reiniciar la aplicación."],
  ["Leave empty for AWS S3. Required for Cloudflare R2, MinIO, etc.", "Déjalo vacío para AWS S3. Es obligatorio para Cloudflare R2, MinIO, etc."],
  ["Keys are stored in the vault database. Set via environment for production.", "Las claves se guardan en la base de datos. En producción, configúralas mediante variables de entorno."],
  ["Set to 0 to keep backups forever. Old backups are purged after each new backup.", "Usa 0 para conservar las copias siempre. Las antiguas se eliminan después de cada copia nueva."],
  ["Backups are always stored locally first. If configured here, they are also uploaded to cloud storage for off-site durability.", "Las copias siempre se guardan primero en local. Si lo configuras aquí, también se suben a la nube."],
  ["Connect Authentik, Authelia, Keycloak, or another standards-compatible identity provider. Local login stays available.", "Conecta Authentik, Authelia, Keycloak u otro proveedor de identidad compatible. El acceso local seguirá disponible."],
  ["Issuer URL and client ID are required before enabling SSO.", "La URL del emisor y el ID de cliente son obligatorios para activar SSO."],
  ["Shows provider button on login page.", "Muestra el botón del proveedor en la página de acceso."],
  ["Clear stored client secret when saving", "Borrar el secreto de cliente guardado al guardar"],
  ["Comma-separated group names granted superuser access.", "Grupos separados por comas que reciben acceso de superusuario."],
  ["Leave blank unless reverse-proxy URL detection is incorrect.", "Déjalo vacío salvo que la detección de URL del proxy inverso sea incorrecta."],
  ["Allow HTTP issuer on trusted LAN", "Permitir emisor HTTP en una LAN de confianza"],
  ["Permanently delete?", "¿Eliminar permanentemente?"],
  ["This will delete the model and all its files immediately. This cannot be undone.", "Esto eliminará inmediatamente el modelo y todos sus archivos. No se puede deshacer."],
  ["This replaces the current database and stored files with the selected backup.", "Esto sustituirá la base de datos y los archivos actuales por la copia seleccionada."],
  ["Download third-party printer images?", "¿Descargar imágenes de impresoras de terceros?"],
  ["Export full library", "Exportar biblioteca completa"],
  ["Import archive", "Importar archivo"],
  ["Library migration", "Migración de biblioteca"],
  ["Data export", "Exportación de datos"],
  ["Storage configuration", "Configuración de almacenamiento"],
  ["Storage backend", "Backend de almacenamiento"],
  ["Storage used", "Almacenamiento usado"],
  ["Local paths", "Rutas locales"],
  ["Local disk", "Disco local"],
  ["Data directory", "Directorio de datos"],
  ["Thumbnail directory", "Directorio de miniaturas"],
  ["S3 connection", "Conexión S3"],
  ["Endpoint URL", "URL del endpoint"],
  ["Access key", "Clave de acceso"],
  ["Secret key", "Clave secreta"],
  ["Backup destination (optional)", "Destino de copias (opcional)"],
  ["Retention (days)", "Retención (días)"],
  ["Save configuration", "Guardar configuración"],
  ["Sign in to modify configuration.", "Inicia sesión para modificar la configuración."],
  ["OpenID Connect", "OpenID Connect"],
  ["Enable SSO login", "Activar acceso SSO"],
  ["Issuer URL", "URL del emisor"],
  ["Client ID", "ID de cliente"],
  ["Client secret", "Secreto de cliente"],
  ["Login button label", "Texto del botón de acceso"],
  ["Configured — enter to replace", "Configurado; escribe para sustituirlo"],
  ["Optional for public clients", "Opcional para clientes públicos"],
  ["Advanced mapping", "Mapeo avanzado"],
  ["Admin groups", "Grupos administradores"],
  ["Username claim", "Atributo de usuario"],
  ["Groups claim", "Atributo de grupos"],
  ["Public callback URL override", "URL pública de retorno personalizada"],
  ["Allow insecure HTTP issuer", "Permitir emisor HTTP no seguro"],
  ["Save SSO settings", "Guardar ajustes SSO"],
  ["Single sign-on settings saved.", "Ajustes de inicio de sesión único guardados."],
  ["Settings sections", "Secciones de ajustes"],
  ["Vault version", "Versión de la bóveda"],
  ["Indexed files", "Archivos indexados"],
  ["All Models", "Todos los modelos"],
  ["New collection", "Nueva colección"],
  ["Saved views", "Vistas guardadas"],
  ["Select Models and folders (S)", "Seleccionar modelos y carpetas (S)"],
  ["Update with current filters", "Actualizar con filtros actuales"],
  ["Select all matching models", "Seleccionar todos los modelos coincidentes"],
  ["Select all on screen", "Seleccionar todo en pantalla"],
  ["Connect folder or NAS", "Conectar carpeta o NAS"],
  ["Clear recent folders", "Borrar carpetas recientes"],
  ["Clear all filters", "Borrar todos los filtros"],
  ["Find a saved view...", "Buscar una vista guardada..."],
  ["Find a saved view", "Buscar una vista guardada"],
  ["Delete saved view?", "¿Eliminar vista guardada?"],
  ["Rename saved view", "Renombrar vista guardada"],
  ["Save current view", "Guardar vista actual"],
  ["Modified saved view", "Vista guardada modificada"],
  ["Create Collection", "Crear colección"],
  ["Delete collection", "Eliminar colección"],
  ["New collection", "Nueva colección"],
  ["Recent folders", "Carpetas recientes"],
  ["No printers configured", "No hay impresoras configuradas"],
  ["No matching tags.", "No hay etiquetas coincidentes."],
  ["No models found", "No se encontraron modelos"],
  ["No results.", "Sin resultados."],
  ["Drop to upload", "Suelta para subir"],
  ["Import from URL", "Importar desde URL"],
  ["Upload files", "Subir archivos"],
  ["Filter outliner...", "Filtrar árbol..."],
  ["Filter tags...", "Filtrar etiquetas..."],
  ["View name", "Nombre de vista"],
  ["Ready to print", "Listo para imprimir"],
  ["Sort models", "Ordenar modelos"],
  ["Drag to reorder", "Arrastra para reordenar"],
  ["On a printer", "En una impresora"],
  ["On printer", "En impresora"],
  ["Recent", "Recientes"],
  ["Filters", "Filtros"],
  ["Layout", "Diseño"],
  ["Density", "Densidad"],
  ["Folder", "Carpeta"],
  ["Duplicate", "Duplicar"],
  ["Rename", "Renombrar"],
  ["Clear all", "Borrar todo"],
  ["Clear", "Borrar"],
  ["Save view", "Guardar vista"],
  ["Updated", "Actualizado"],
  ["Updating...", "Actualizando..."],
  ["selected", "seleccionados"],
  ["subcollection", "subcolección"],
  ["more", "más"],
  ["Any location", "Cualquier ubicación"],
  ["On a printer", "En una impresora"],
  ["Vault only", "Solo en la bóveda"],
  ["Filter outline...", "Filtrar árbol..."],
  ["Show printer image", "Mostrar imagen de impresora"],
  ["Model card metrics", "Métricas de tarjetas de modelo"],
  ["Model metadata", "Metadatos del modelo"],
  ["Print tracking", "Seguimiento de impresión"],
  ["Trash retention", "Retención de papelera"],
  ["Deleted models", "Modelos eliminados"],
  ["Latest changes", "Últimos cambios"],
  ["Check for updates", "Buscar actualizaciones"],
  ["Create users, assign vault admins, disable accounts, and reset passwords.", "Crea usuarios, asigna administradores, desactiva cuentas y restablece contraseñas."],
  ["Assign view, edit, or admin access per user. Child collections inherit parent grants.", "Asigna acceso de lectura, edición o administración por usuario. Las colecciones hijas heredan los permisos."],
  ["Create credentials for scripts and integrations, then exchange them for a JWT at login.", "Crea credenciales para scripts e integraciones y canjéalas por un JWT al iniciar sesión."],
  ["Copy this key now. It will only be shown once.", "Copia esta clave ahora. Solo se mostrará una vez."],
  ["Create a full backup of the database and all stored files right now.", "Crea ahora una copia completa de la base de datos y los archivos guardados."],
  ["Recover the vault database and stored files from a previous backup.", "Recupera la base de datos y los archivos desde una copia anterior."],
  ["Mirror a folder — on the server or a NAS — in place: files are indexed where they live, never copied. Local folders can be watched in real time; all folders support scheduled and manual scans. Off by default.", "Refleja una carpeta del servidor o NAS sin copiarla: los archivos se indexan donde están. Las carpetas locales admiten vigilancia en tiempo real y todas admiten análisis programados o manuales. Desactivado por defecto."],
  ["Watching gives near-real-time updates on local folders. Network folders (NAS over NFS/SMB) don't deliver file events, so they fall back to the schedule above.", "La vigilancia actualiza casi en tiempo real las carpetas locales. Las carpetas de red no emiten eventos y usan la programación indicada."],
  ["Add a folder below to start mirroring it into your vault.", "Añade una carpeta para empezar a reflejarla en tu bóveda."],
  ["Add a channel to start receiving print and printer alerts.", "Añade un canal para recibir alertas de impresiones e impresoras."],
  ["Send webhook, Discord, Telegram, or ntfy alerts on print and printer events.", "Envía alertas por webhook, Discord, Telegram o ntfy sobre impresiones e impresoras."],
  ["Only an administrator can manage notification channels.", "Solo un administrador puede gestionar canales de notificación."],
  ["Track filament inventory and per-print consumption with a self-hosted Spoolman instance. Off by default.", "Controla inventario y consumo de filamento con una instancia propia de Spoolman. Desactivado por defecto."],
  ["Only an administrator can configure Spoolman.", "Solo un administrador puede configurar Spoolman."],
  ["Decrements the selected spool by measured filament when a print completes (Moonraker-measured prints only).", "Descuenta del carrete seleccionado el filamento medido al terminar una impresión (solo mediciones de Moonraker)."],
  ["Connect a MakerWorld (Bambu) account so model &amp; collection imports can download files", "Conecta una cuenta de MakerWorld (Bambu) para descargar archivos al importar modelos y colecciones"],
  ["Only an administrator can connect MakerWorld.", "Solo un administrador puede conectar MakerWorld."],
  ["Your password is sent once to Bambu to obtain a session token and is never stored. MakerWorld usually emails a verification code next.", "La contraseña se envía una vez a Bambu para obtener un token de sesión y nunca se guarda. MakerWorld suele enviar después un código por correo."],
  ["Sessions expire periodically — if imports start failing with a login error, disconnect and connect again.", "Las sesiones caducan periódicamente. Si las importaciones fallan por acceso, desconecta y vuelve a conectar."],
  ["Choose whether printer cards include a visual. Plain cards remain more compact and information-dense.", "Elige si las tarjetas de impresora incluyen imagen. Sin imagen son más compactas."],
  ["Adds a brand-neutral printer visual above each card.", "Añade una imagen neutral sobre cada tarjeta."],
  ["Automatically promote a revision to known-good after its first successful print. A manual failed/archived verdict is never overridden.", "Marca automáticamente una revisión como válida tras su primera impresión correcta. Nunca sustituye un estado manual fallido o archivado."],
  ["Currency used to display cost figures in statistics and filament pricing.", "Moneda usada para costes en estadísticas y precios de filamento."],
  ["Choose which 3 stats appear on each model card in the grid.", "Elige las 3 estadísticas visibles en cada tarjeta de modelo."],
  ["Choose which metadata fields appear on model detail pages.", "Elige los metadatos visibles en las páginas de modelo."],
  ["Soft-deleted models stay restorable until the retention window expires.", "Los modelos eliminados se pueden restaurar hasta que venza la retención."],
  ["Restore models or remove them permanently from storage.", "Restaura modelos o elimínalos permanentemente del almacenamiento."],
  ["Self-hosted asset management for 3D printing workflows.", "Gestión autohospedada de recursos para impresión 3D."],
  ["What changed in the current release", "Cambios de la versión actual"],
  ["Select a user to review collection grants.", "Selecciona un usuario para revisar permisos de colecciones."],
  ["Initial password: at least 8 characters.", "Contraseña inicial: mínimo 8 caracteres."],
  ["Sign in to create API keys.", "Inicia sesión para crear claves API."],
  ["Sign in to manage the trash.", "Inicia sesión para gestionar la papelera."],
  ["No active API keys.", "No hay claves API activas."],
  ["No backups found.", "No se encontraron copias."],
  ["No notification channels yet", "Aún no hay canales de notificación"],
  ["No printers configured.", "No hay impresoras configuradas."],
  ["No shared volumes yet", "Aún no hay volúmenes compartidos"],
  ["No users.", "No hay usuarios."],
  ["Trash is empty.", "La papelera está vacía."],
  ["Collection access", "Acceso a colecciones"],
  ["API keys", "Claves API"],
  ["API key", "Clave API"],
  ["Initial password", "Contraseña inicial"],
  ["New password", "Nueva contraseña"],
  ["Reset password", "Restablecer contraseña"],
  ["Revoke API key", "Revocar clave API"],
  ["Copy API key", "Copiar clave API"],
  ["Copy OrcaSlicer post-processing command", "Copiar comando de posprocesado de OrcaSlicer"],
  ["Collection access", "Acceso a colecciones"],
  ["Select collection", "Seleccionar colección"],
  ["Select user", "Seleccionar usuario"],
  ["Remove collection access", "Quitar acceso a colección"],
  ["Refresh collection access", "Actualizar acceso a colecciones"],
  ["Superuser access is required.", "Se requiere acceso de superusuario."],
  ["Manual backup", "Copia manual"],
  ["Backup now", "Crear copia ahora"],
  ["Refresh backups", "Actualizar copias"],
  ["Restore backup", "Restaurar copia"],
  ["Restore backup?", "¿Restaurar copia?"],
  ["Shared volumes", "Volúmenes compartidos"],
  ["Add a folder", "Añadir carpeta"],
  ["Remove external library?", "¿Quitar biblioteca externa?"],
  ["Remove library", "Quitar biblioteca"],
  ["Mirror subfolders as collections", "Reflejar subcarpetas como colecciones"],
  ["Real-time watching", "Vigilancia en tiempo real"],
  ["Scan schedule", "Programación de análisis"],
  ["Auto-scan enabled", "Análisis automático activado"],
  ["Single collection (flat)", "Una colección (plana)"],
  ["Some files could not be indexed", "Algunos archivos no pudieron indexarse"],
  ["Recent deliveries", "Entregas recientes"],
  ["Send a test notification", "Enviar notificación de prueba"],
  ["Create channel", "Crear canal"],
  ["Save changes", "Guardar cambios"],
  ["Delete channel", "Eliminar canal"],
  ["Edit channel", "Editar canal"],
  ["All printers", "Todas las impresoras"],
  ["MakerWorld account", "Cuenta de MakerWorld"],
  ["MakerWorld is connected.", "MakerWorld está conectado."],
  ["MakerWorld password", "Contraseña de MakerWorld"],
  ["Verification code", "Código de verificación"],
  ["Use password instead", "Usar contraseña"],
  ["Google account? Paste token", "¿Cuenta de Google? Pega el token"],
  ["Session token", "Token de sesión"],
  ["Session stored", "Sesión guardada"],
  ["Disconnect", "Desconectar"],
  ["Test connection", "Probar conexión"],
  ["Enable Spoolman integration", "Activar integración con Spoolman"],
  ["Write consumption back to Spoolman", "Registrar consumo en Spoolman"],
  ["Only if Spoolman sits behind an authenticating proxy", "Solo si Spoolman está detrás de un proxy con autenticación"],
  ["Printer cards", "Tarjetas de impresora"],
  ["Display currency", "Moneda mostrada"],
  ["Auto-mark known good on successful print", "Marcar como válida tras una impresión correcta"],
  ["Show printer image on printer cards", "Mostrar imagen en tarjetas de impresora"],
  ["Refresh trash", "Actualizar papelera"],
  ["View release", "Ver versión"],
  ["View", "Ver"],
  ["Edit", "Editar"],
  ["Admin", "Administrador"],
  ["User", "Usuario"],
  ["Role", "Rol"],
  ["Name", "Nombre"],
  ["Email", "Correo"],
  ["Password", "Contraseña"],
  ["Username", "Usuario"],
  ["Create", "Crear"],
  ["Generate", "Generar"],
  ["Grant", "Conceder"],
  ["Remove", "Quitar"],
  ["Cancel", "Cancelar"],
  ["Enabled", "Activado"],
  ["Disabled", "Desactivado"],
  ["Events", "Eventos"],
  ["Type", "Tipo"],
  ["Authorization", "Autorización"],
  ["Inventory", "Inventario"],
  ["Base URL", "URL base"],
  ["Key name", "Nombre de clave"],
  ["Collection", "Colección"],
  ["Download", "Descargar"],
  ["Printer artwork will load from OrcaSlicer's GitHub repository. Images may be copyrighted or trademarked by their creators or printer manufacturers and remain subject to their original licenses. PrintStash does not own or redistribute them. Continue only if this use is permitted where you live.", "Las imágenes de impresoras se cargarán desde el repositorio de OrcaSlicer. Pueden tener derechos de autor o marcas de sus creadores o fabricantes y conservan sus licencias originales. PrintStash no las posee ni redistribuye. Continúa solo si este uso está permitido donde vives."],
  ["Leave empty for AWS S3.", "Déjalo vacío para AWS S3."],
  ["Review release notes before updating your self-hosted installation.", "Revisa las notas de versión antes de actualizar tu instalación."],
  ["Add channel", "Añadir canal"],
  ["Auto-disabled", "Desactivado automáticamente"],
  ["Backing up…", "Creando copia…"],
  ["Custom cron…", "Cron personalizado…"],
  ["Orca command", "Comando de Orca"],
  ["Notifications", "Notificaciones"],
  ["Scopes", "Ámbitos"],
  ["Slot", "Posición"],
  ["This vault is running v", "Esta bóveda usa v"],
  ["Update available: v", "Actualización disponible: v"],
  ["has no direct collection access.", "no tiene acceso directo a colecciones."],
  ["added ·", "añadido ·"],
  ["updated ·", "actualizado ·"],
  ["removed", "eliminado"],
  ["disabled", "desactivado"],
  ["paused", "pausado"],
  ["shown", "visibles"],
  ["models", "modelos"],
  ["files", "archivos"],
  ["left", "restantes"],
  ["of", "de"],
  ["· Expires", "· Caduca"],
  ["· last scan", "· último análisis"],
  ["Storage", "Almacenamiento"],
  ["System", "Sistema"],
  ["Database", "Base de datos"],
  ["Connected", "Conectada"],
  ["Unknown", "Desconocido"],
  ["Models", "Modelos"],
  ["Documents", "Documentos"],
  ["Files", "Archivos"],
  ["Printers", "Impresoras"],
  ["Collections", "Colecciones"],
  ["Tags", "Etiquetas"],
  ["Users", "Usuarios"],
  ["Upload", "Subir"],
  ["Favorites", "Favoritos"],
  ["Select", "Seleccionar"],
  ["Newest", "Más recientes"],
  ["Display", "Vista"],
  ["Loading...", "Cargando..."],
  ["Loading", "Cargando"],
  ["Exporting", "Exportando"],
  ["Importing", "Importando"],
  ["Saving...", "Guardando..."],
  ["Saving", "Guardando"],
  ["Saved", "Guardado"],
  ["Save", "Guardar"],
  ["Refresh", "Actualizar"],
  ["Restore", "Restaurar"],
  ["Delete forever", "Eliminar definitivamente"],
  ["Delete", "Eliminar"],
  ["Download & enable", "Descargar y activar"],
  ["Backup", "Copia de seguridad"],
  ["Bucket", "Bucket"],
  ["Region", "Región"],
  ["Credentials", "Credenciales"],
  ["Local", "Local"],
  ["Never", "Nunca"],
  ["Days", "Días"],
  ["Reset", "Restablecer"],
  ["Show all", "Mostrar todo"],
  ["Hide all", "Ocultar todo"],
  ["Currency", "Moneda"],
  ["Overview", "Resumen"],
];

const TRANSLATED_PROPS = new Set([
  "aria-label",
  "aria-description",
  "description",
  "hint",
  "label",
  "placeholder",
  "title",
  "confirmLabel",
]);

export function translateUiText(locale: Locale, value: string): string {
  if (locale !== "es" || !value.trim()) return value;
  let translated = value
    .replace(/(\d+) models? total/gi, "$1 modelos en total")
    .replace(/(\d+) stored objects?/gi, "$1 objetos guardados")
    .replace(/(\d+) days? ago/gi, "hace $1 días")
    .replace(/(\d+) files?/gi, "$1 archivos")
    .replace(/(\d+) source/gi, "$1 originales");
  for (const [english, spanish] of [...ES_PHRASES].sort(
    ([left], [right]) => right.length - left.length,
  )) {
    const escaped = english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const start = /^\w/.test(english) ? "\\b" : "";
    const end = /\w$/.test(english) ? "\\b" : "";
    translated = translated.replace(new RegExp(`${start}${escaped}${end}`, "g"), spanish);
  }
  return translated;
}

function localizeNode(node: ReactNode, locale: Locale): ReactNode {
  if (typeof node === "string") return translateUiText(locale, node);
  if (Array.isArray(node)) return node.map((child) => localizeNode(child, locale));
  if (!isValidElement(node)) return node;

  const element = node as ReactElement<Record<string, unknown>>;
  const props: Record<string, unknown> = {};
  for (const [name, value] of Object.entries(element.props)) {
    if (TRANSLATED_PROPS.has(name) && typeof value === "string") {
      props[name] = translateUiText(locale, value);
    }
  }
  if ("children" in element.props) {
    props.children = Children.map(element.props.children as ReactNode, (child) =>
      localizeNode(child, locale),
    );
  }
  return cloneElement(element, props);
}

export function Localized({ children }: { children: ReactNode }) {
  const locale = useOptionalI18n()?.locale ?? "en";
  return <>{localizeNode(children, locale)}</>;
}
